import { Lead, Deal, Contact, Company, Task, Activity, DashboardMetrics } from "@/types/crm";

export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    created_at: "2026-01-15T10:00:00Z",
    name: "Apex Global Cloud",
    domain: "apexcloud.io",
    industry: "Enterprise SaaS",
    size: "500+",
    tier: "Enterprise",
    annual_revenue: 45000000,
    phone: "+1 (555) 234-5678",
    city: "San Francisco",
    country: "USA",
    status: "active",
    contact_count: 4,
    deal_count: 2,
  },
  {
    id: "comp-2",
    created_at: "2026-02-01T11:30:00Z",
    name: "FinPulse Analytics",
    domain: "finpulse.ai",
    industry: "Financial Technology",
    size: "51-200",
    tier: "Mid-Market",
    annual_revenue: 12500000,
    phone: "+1 (555) 345-6789",
    city: "New York",
    country: "USA",
    status: "active",
    contact_count: 2,
    deal_count: 1,
  },
  {
    id: "comp-3",
    created_at: "2026-02-10T14:15:00Z",
    name: "Novus Health Systems",
    domain: "novushealth.org",
    industry: "Healthcare / MedTech",
    size: "201-500",
    tier: "Enterprise",
    annual_revenue: 28000000,
    phone: "+1 (555) 456-7890",
    city: "Boston",
    country: "USA",
    status: "active",
    contact_count: 3,
    deal_count: 2,
  },
  {
    id: "comp-4",
    created_at: "2026-02-18T09:00:00Z",
    name: "Vanguard Robotics",
    domain: "vanguardrobotics.com",
    industry: "Industrial Automation",
    size: "51-200",
    tier: "Mid-Market",
    annual_revenue: 8500000,
    phone: "+1 (555) 567-8901",
    city: "Austin",
    country: "USA",
    status: "prospect",
    contact_count: 1,
    deal_count: 1,
  },
  {
    id: "comp-5",
    created_at: "2026-02-25T16:45:00Z",
    name: "Starlight Cyber",
    domain: "starlightcyber.security",
    industry: "Cybersecurity",
    size: "11-50",
    tier: "Startup",
    annual_revenue: 3200000,
    phone: "+1 (555) 678-9012",
    city: "Seattle",
    country: "USA",
    status: "prospect",
    contact_count: 2,
    deal_count: 1,
  },
];

export const mockContacts: Contact[] = [
  {
    id: "cont-1",
    created_at: "2026-01-16T10:30:00Z",
    first_name: "Elena",
    last_name: "Rostova",
    email: "elena.rostova@apexcloud.io",
    phone: "+1 (555) 234-5679",
    title: "Chief Technology Officer",
    company_id: "comp-1",
    company_name: "Apex Global Cloud",
    is_primary: true,
    status: "active",
    last_contacted_at: "2026-03-01T15:00:00Z",
  },
  {
    id: "cont-2",
    created_at: "2026-01-18T14:00:00Z",
    first_name: "Marcus",
    last_name: "Vance",
    email: "m.vance@apexcloud.io",
    phone: "+1 (555) 234-5680",
    title: "VP of Cloud Infrastructure",
    company_id: "comp-1",
    company_name: "Apex Global Cloud",
    is_primary: false,
    status: "active",
    last_contacted_at: "2026-02-27T11:00:00Z",
  },
  {
    id: "cont-3",
    created_at: "2026-02-02T13:00:00Z",
    first_name: "Sarah",
    last_name: "Jenkins",
    email: "sarah.j@finpulse.ai",
    phone: "+1 (555) 345-6790",
    title: "Head of Product",
    company_id: "comp-2",
    company_name: "FinPulse Analytics",
    is_primary: true,
    status: "active",
    last_contacted_at: "2026-03-02T09:30:00Z",
  },
  {
    id: "cont-4",
    created_at: "2026-02-12T16:00:00Z",
    first_name: "Dr. Arthur",
    last_name: "Pendleton",
    email: "arthur.p@novushealth.org",
    phone: "+1 (555) 456-7891",
    title: "Director of Digital Transformation",
    company_id: "comp-3",
    company_name: "Novus Health Systems",
    is_primary: true,
    status: "active",
    last_contacted_at: "2026-02-28T14:20:00Z",
  },
  {
    id: "cont-5",
    created_at: "2026-02-20T10:00:00Z",
    first_name: "Liam",
    last_name: "Chen",
    email: "liam@vanguardrobotics.com",
    phone: "+1 (555) 567-8902",
    title: "VP of Engineering",
    company_id: "comp-4",
    company_name: "Vanguard Robotics",
    is_primary: true,
    status: "active",
    last_contacted_at: "2026-03-01T10:00:00Z",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    created_at: "2026-02-28T10:00:00Z",
    first_name: "David",
    last_name: "Sterling",
    email: "dsterling@hyperionops.com",
    phone: "+1 (555) 888-1212",
    company: "Hyperion Operations",
    title: "Head of Operations",
    status: "new",
    source: "website",
    score: 85,
    estimated_value: 65000,
    notes: "Requested a live enterprise product demo on pricing tier 2.",
  },
  {
    id: "lead-2",
    created_at: "2026-02-26T14:30:00Z",
    first_name: "Rachel",
    last_name: "Kim",
    email: "rachel.kim@quantumscale.io",
    phone: "+1 (555) 888-3434",
    company: "QuantumScale AI",
    title: "Chief Product Officer",
    status: "qualified",
    source: "referral",
    score: 92,
    estimated_value: 120000,
    notes: "Referred by Apex Global CTO. Ready for custom MSA terms.",
  },
  {
    id: "lead-3",
    created_at: "2026-02-24T09:15:00Z",
    first_name: "Mateo",
    last_name: "Silva",
    email: "mateo@latamlogistics.net",
    phone: "+1 (555) 888-5656",
    company: "LatAm Logistics Corp",
    title: "VP Supply Chain",
    status: "contacted",
    source: "cold_outreach",
    score: 68,
    estimated_value: 48000,
    notes: "Followed up via email regarding multi-branch inventory tracking.",
  },
  {
    id: "lead-4",
    created_at: "2026-02-20T11:00:00Z",
    first_name: "Chloe",
    last_name: "Dubois",
    email: "chloe@aetherdesign.fr",
    phone: "+33 1 42 68 55 00",
    company: "Aether Design Studios",
    title: "Managing Partner",
    status: "lost",
    source: "conference",
    score: 30,
    estimated_value: 18000,
    notes: "Budget deferred to Q4 2026. Stay in touch.",
  },
  {
    id: "lead-5",
    created_at: "2026-03-01T08:45:00Z",
    first_name: "Jonathan",
    last_name: "Drake",
    email: "jdrake@crestviewcapital.com",
    phone: "+1 (555) 888-7878",
    company: "Crestview Capital Partners",
    title: "Managing Director",
    status: "new",
    source: "linkedin",
    score: 78,
    estimated_value: 95000,
    notes: "Expressed interest in CRM compliance reporting features.",
  },
];

export const mockDeals: Deal[] = [
  {
    id: "deal-1",
    created_at: "2026-01-20T10:00:00Z",
    title: "Apex Cloud - Enterprise License & Migration",
    amount: 145000,
    stage: "negotiation",
    probability: 80,
    expected_close_date: "2026-03-25",
    company_id: "comp-1",
    company_name: "Apex Global Cloud",
    contact_id: "cont-1",
    contact_name: "Elena Rostova",
  },
  {
    id: "deal-2",
    created_at: "2026-02-05T15:00:00Z",
    title: "FinPulse - Real-time Pipeline Intelligence",
    amount: 82000,
    stage: "proposal",
    probability: 60,
    expected_close_date: "2026-04-10",
    company_id: "comp-2",
    company_name: "FinPulse Analytics",
    contact_id: "cont-3",
    contact_name: "Sarah Jenkins",
  },
  {
    id: "deal-3",
    created_at: "2026-02-15T09:30:00Z",
    title: "Novus Health - Patient Data Sync & CRM Core",
    amount: 190000,
    stage: "discovery",
    probability: 30,
    expected_close_date: "2026-05-15",
    company_id: "comp-3",
    company_name: "Novus Health Systems",
    contact_id: "cont-4",
    contact_name: "Dr. Arthur Pendleton",
  },
  {
    id: "deal-4",
    created_at: "2026-01-10T11:00:00Z",
    title: "Novus Health - Phase 1 Telemetry Integration",
    amount: 64000,
    stage: "won",
    probability: 100,
    expected_close_date: "2026-02-15",
    company_id: "comp-3",
    company_name: "Novus Health Systems",
    contact_id: "cont-4",
    contact_name: "Dr. Arthur Pendleton",
  },
  {
    id: "deal-5",
    created_at: "2026-02-22T13:45:00Z",
    title: "Vanguard Robotics - Industrial Fleet CRM",
    amount: 55000,
    stage: "proposal",
    probability: 50,
    expected_close_date: "2026-04-30",
    company_id: "comp-4",
    company_name: "Vanguard Robotics",
    contact_id: "cont-5",
    contact_name: "Liam Chen",
  },
  {
    id: "deal-6",
    created_at: "2026-01-05T16:00:00Z",
    title: "Legacy Systems Transition",
    amount: 32000,
    stage: "lost",
    probability: 0,
    expected_close_date: "2026-02-01",
    company_id: "comp-5",
    company_name: "Starlight Cyber",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    created_at: "2026-03-01T09:00:00Z",
    title: "Finalize MSA Legal Terms with Elena Rostova",
    description: "Send redline version 3 with customized SLA and payment net-45 terms.",
    due_date: "2026-03-06T17:00:00Z",
    priority: "urgent",
    status: "in_progress",
    related_to_type: "deal",
    related_to_id: "deal-1",
    related_to_title: "Apex Cloud - Enterprise License",
  },
  {
    id: "task-2",
    created_at: "2026-03-02T10:15:00Z",
    title: "Prepare technical architecture proposal for FinPulse",
    description: "Include security compliance whitepaper and SOC2 certs.",
    due_date: "2026-03-08T18:00:00Z",
    priority: "high",
    status: "pending",
    related_to_type: "deal",
    related_to_id: "deal-2",
    related_to_title: "FinPulse - Real-time Pipeline Intelligence",
  },
  {
    id: "task-3",
    created_at: "2026-03-02T14:00:00Z",
    title: "Discovery Zoom Call with Dr. Arthur Pendleton",
    description: "Scope patient sync constraints and HIPAA data routing.",
    due_date: "2026-03-10T15:00:00Z",
    priority: "medium",
    status: "pending",
    related_to_type: "contact",
    related_to_id: "cont-4",
    related_to_title: "Dr. Arthur Pendleton",
  },
  {
    id: "task-4",
    created_at: "2026-02-27T11:30:00Z",
    title: "Send intro email and product deck to David Sterling",
    description: "Follow up after website inquiry submission.",
    due_date: "2026-03-03T12:00:00Z",
    priority: "medium",
    status: "completed",
    related_to_type: "lead",
    related_to_id: "lead-1",
    related_to_title: "David Sterling (Hyperion)",
  },
  {
    id: "task-5",
    created_at: "2026-03-01T16:00:00Z",
    title: "Quarterly pipeline review with sales leadership",
    description: "Review conversion metrics and Q1 targets.",
    due_date: "2026-03-15T16:00:00Z",
    priority: "low",
    status: "pending",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    created_at: "2026-03-03T19:30:00Z",
    type: "deal_stage_changed",
    title: "Deal stage progressed to Negotiation",
    description: "Apex Cloud Enterprise License moved from Proposal to Negotiation ($145,000)",
    user_name: "Alex Morgan",
    entity_type: "deal",
    entity_id: "deal-1",
  },
  {
    id: "act-2",
    created_at: "2026-03-02T16:15:00Z",
    type: "meeting",
    title: "Executive Demo with Sarah Jenkins",
    description: "Walked through custom pipeline stages and automated notifications for FinPulse.",
    user_name: "Alex Morgan",
    entity_type: "contact",
    entity_id: "cont-3",
  },
  {
    id: "act-3",
    created_at: "2026-03-01T11:00:00Z",
    type: "lead_converted",
    title: "Qualified Inbound Lead: Rachel Kim",
    description: "Assigned lead score 92 based on company size and executive title.",
    user_name: "Jordan Lee",
    entity_type: "lead",
    entity_id: "lead-2",
  },
  {
    id: "act-4",
    created_at: "2026-02-28T14:40:00Z",
    type: "email",
    title: "Outreach sent to Mateo Silva",
    description: "Discussed supply chain integration features for LatAm Logistics.",
    user_name: "Jordan Lee",
    entity_type: "lead",
    entity_id: "lead-3",
  },
  {
    id: "act-5",
    created_at: "2026-02-25T17:00:00Z",
    type: "call",
    title: "Check-in call with Marcus Vance",
    description: "Confirmed infrastructure specifications for Apex Cloud cloud deployment.",
    user_name: "Alex Morgan",
    entity_type: "contact",
    entity_id: "cont-2",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  total_revenue: 536000,
  pipeline_value: 472000,
  active_deals_count: 5,
  win_rate: 68,
  active_leads_count: 4,
  pending_tasks_count: 4,
  deals_by_stage: {
    discovery: { count: 1, total_amount: 190000 },
    proposal: { count: 2, total_amount: 137000 },
    negotiation: { count: 1, total_amount: 145000 },
    won: { count: 1, total_amount: 64000 },
    lost: { count: 1, total_amount: 32000 },
  },
  monthly_revenue_history: [
    { month: "Nov", won: 42000, pipeline: 120000 },
    { month: "Dec", won: 58000, pipeline: 185000 },
    { month: "Jan", won: 75000, pipeline: 240000 },
    { month: "Feb", won: 64000, pipeline: 310000 },
    { month: "Mar", won: 95000, pipeline: 472000 },
  ],
  recent_activities: mockActivities,
};
